### ISSUE TITLE
Login via Clever takes me to sign-in screen

### ISSUE THREAD

**Issue by tonyamurray** [yeatmanlab/roar-dashboard#103]
I created an administration called Test Connectivity and assigned it to BRSSD.  I think I selected the 6 schools during the creation.  
I used the Clever impersonation feature to log in as a student from Central.  (I sorted by first name and chose the first 1st grade student).  I was given the sign-in page (which has fields for name and password) instead of the page with the games.

**Comment by richford** [comment]
Closed via #107
