### ISSUE TITLE
Vuelidate all forms

### ISSUE THREAD

**Issue by richford** [yeatmanlab/roar-dashboard#44]
Create administration:
- all fields are required
- at least one org must be assigned
- at least one task is required
- all `taskId`s in the assessments array must be unique

Mass uploader:
- No vuelidate necessary b/c @kellyel did all sorts of awesome validation in pure js

Create org:
- All fields are required
- Parent org is required for schools and classes
- Grade is required for class

**Comment by kellyel** [comment]
Mostly addressed by #49. All criteria met for create administration, create org has text fields required. We decided to complete the rest of the validation on this form later as that form is not going to be widely used for MVP.
