### ISSUE TITLE
Game loaded correctly SWR

### ISSUE THREAD

**Issue by ksmontville** [yeatmanlab/roar-dashboard#866]
Test if the app ran correctly and returned to the dashboard

**Comment by ksmontville** [comment]
Each game will fail to launch on the first try, resulting in the alert/error shown in the attached screenshots.

After accepting the alert error, the game will launch as expected.

This behavior does not exist on production or staging environments.

![Image](https://github.com/user-attachments/assets/b75bf56e-2146-4bf4-a61a-c2ce0b2dc055)
![Image](https://github.com/user-attachments/assets/bb82e62a-cb34-4ff8-99f0-45353fa25a83)

**Comment by Emily-ejag** [comment]
I experienced the same: ![Image](https://github.com/user-attachments/assets/76e46bc3-6add-4fc4-a625-7e0fd0370acb)
![Image](https://github.com/user-attachments/assets/78293712-392d-42ca-849a-18f35f5059b6)

**Comment by maximilianoertel** [comment]
Thanks for flagging, this should be ready for re-testing on the [PR environment](https://roar-staging--pr748-ref-318-query-compos-licip3pp.web.app/)

**Comment by richford** [comment]
I just retested and it passed.
