### ISSUE TITLE
Returning to the same administration selected after the game

### ISSUE THREAD

**Issue by Emily-ejag** [yeatmanlab/roar-dashboard#873]
When a user has multiple administrations (English and Spanish, for example), they select a game from one administration to play. After finishing the game, instead of being returned to the correct administration they were playing, they are redirected to a different administration. This issue affects the flow for students who need to continue playing games in their originally selected administration.

**Steps to Reproduce:**

1. Assign a user to multiple administrations (e.g., English and Spanish).
2. Select a game from one of the administrations (e.g., English).
3. Play the game to completion.
4. Observe that after the game, the user is redirected to another administration (e.g., Spanish) instead of the administration they initially selected.

**Expected Behavior:**
After finishing the game, the user should be returned to the same administration they were playing from, not switched to another one.

**Actual Behavior:**
The user is redirected to a different administration after completing the game.

**Impact:**
This issue can be confusing for students, especially when switching between different language administrations (e.g., English and Spanish), as they need to manually reselect the administration they were playing on.

**Comment by maximilianoertel** [comment]
Closing as marked as `passing` in the project board
