### ISSUE TITLE
Administrators can see administration list after navigating back to home page

### ISSUE THREAD

**Issue by richford** [yeatmanlab/roar-dashboard#886]
I also noticed that if one returns to administrator home from another route, the administration list is empty.

### To reproduce,
1. Log in as an administrator (e.g. demo-district-admin with password: "password") or super-administrator.
2. Allow the administration list to load completely
3. Navigate to another route (e.g. list-orgs or create-administration)
4. Return to the administrator home (either by clicking on the ROAR logo or on the Administrations > View Administrations menu item).

### Expected behavior:

Page displays the same administrations seen in step 2.

**Comment by richford** [comment]
### Actual behavior:

![Image](https://github.com/user-attachments/assets/a0f4bfda-793a-4615-b5ef-49461413641f)

**Comment by richford** [comment]
This may be related to something I noticed on the participant home page. When a participant first logs in, the "You have no assignments" screen briefly flashes. Then it updates with their assignments. Ideally, we would wait until we have retrieved their assignments before assessing whether to show the "You have no assignments" screen. I didn't make an issue of that one because I believe it exists on prod and was not introduced by @maximilianoertel's PR.

However, is it possible that the same thing is happening to administrators and that the dashboard is using the cached "no administrations" result to display the list of administrations?

**Comment by maximilianoertel** [comment]
I noticed that as well and have been looking into it, but the participant homepage is a bit more complex than the administrator homepage. The PR for the latter is ready for review and I hope to have a fix for the participant homepage ready shortly!
